# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ut4OrSJZ0ozx2lsrFvns7AKh3kPHl4f6
"""

import streamlit as st

st.title("مرحباً بكِ في عالم البرمجة 👋")

name = st.text_input("ما هو اسمكِ؟")
age = st.number_input("كم عمركِ؟", min_value=1)
gender = st.selectbox("النوع", ["بنت", "ولد"])

if name:
    st.success(f"أهلاً بكِ يا {name} في تطبيقكِ الأول!")

    if age < 20:
        st.info("المستقبل أمامكِ لتكوني مبرمجة محترفة!")

    st.balloons()
    st.snow()

if st.button("اضغطي هنا للمفاجأة"):
    st.toast("إنتي مبرمجة شاطرة!")
    st.balloons()